DROP TABLE LoginAttempts;

CREATE TABLE LoginAttempts
(USERNAME varchar(20) NOT NULL,
IP varchar(20) NOT NULL,
LOGINTIME varchar(20) NOT NULL,
LOGINATTEMPT INT NOT NULL,
PRIMARY KEY(IP)
);
COMMIT;
